name = "DICOMClient"
uuid = "552a5c7d-7ce6-47fd-927f-656bb472b0c1"
authors = ["Dilum Aluthge", "Brown Center for Biomedical Informatics", "JuliaHealth organization", "contributors"]
version = "0.1.0"

[compat]
julia = "1.3"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
